# Generated by Django 5.1.4 on 2025-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Sipariş Adresi'), ('billibg', 'Fatura Adresi')], max_length=10),
        ),
    ]
