# Generated by Django 5.1.4 on 2025-12-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_address_district_address_full_name_address_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default='', help_text='Örn: Evim, İş Yerim', max_length=50, verbose_name='Adres Başlığı'),
            preserve_default=False,
        ),
    ]
