# Generated by Django 5.1.4 on 2026-01-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_address_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tc_kimlik_no',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
