"""
Django settings for angelesyasam project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


SECRET_KEY = os.environ.get('SECRET_KEY')

DEBUG = os.getenv("DEBUG", "False").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'users',
    'products',
    'orders',
    'payments',
    'pages',
    'cart',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'angelesyasam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_counts',
                'core.context_processors.categories_processor',
                'core.context_processors.store_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'angelesyasam.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "ecommerce_db"),
        "USER": os.getenv("POSTGRES_USER", "ecommerce_user"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "local-development-only"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True  # Locale formatlarını kullan (tarih, sayı formatları)

USE_TZ = True

# Türkçe locale için
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')  # This is where your source static files are
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # This is where collectstatic will put files

# Add this for media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Redis

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


# User
AUTH_USER_MODEL = "users.CustomUser"

# Login/Logout URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'profile'
LOGOUT_REDIRECT_URL = 'home'

IYZICO_API_KEY = os.getenv("IYZICO_API_KEY", "")
IYZICO_SECRET_KEY = os.getenv("IYZICO_SECRET_KEY", "")
IYZICO_BASE_URL = os.getenv(
    "IYZICO_BASE_URL",
    "https://sandbox-api.iyzipay.com",
)

APP_BASE_URL = os.getenv("APP_BASE_URL", "http://localhost:8080").rstrip("/")

STORE_NAME = os.getenv("STORE_NAME", "Demo Health Store")
STORE_LEGAL_NAME = os.getenv("STORE_LEGAL_NAME", "Demo Medikal Ltd. Şti.")
STORE_TAGLINE = os.getenv("STORE_TAGLINE", "DEMO MEDİKAL")
STORE_EMAIL = os.getenv("STORE_EMAIL", "support@demo-store.example")
STORE_SUPPORT_EMAIL = os.getenv("STORE_SUPPORT_EMAIL", STORE_EMAIL)
STORE_PRIVACY_EMAIL = os.getenv("STORE_PRIVACY_EMAIL", "privacy@demo-store.example")
STORE_LEGAL_EMAIL = os.getenv("STORE_LEGAL_EMAIL", "legal@demo-store.example")
STORE_PHONE = os.getenv("STORE_PHONE", "+90 555 000 00 00")
STORE_PHONE_TEL = os.getenv("STORE_PHONE_TEL", "905550000000")
STORE_WHATSAPP_URL = os.getenv("STORE_WHATSAPP_URL", "https://wa.me/905550000000")
STORE_ADDRESS = os.getenv(
    "STORE_ADDRESS",
    "Demo Mahallesi, Örnek Sokak No:1, 34000 Demoşehir / Türkiye",
)
STORE_CITY = os.getenv("STORE_CITY", "Demoşehir")
STORE_DOMAIN = os.getenv("STORE_DOMAIN", "demo-store.example")
STORE_URL = os.getenv("STORE_URL", APP_BASE_URL)
STORE_MERSIS = os.getenv("STORE_MERSIS", "0000000000000000")
STORE_TAX_NUMBER = os.getenv("STORE_TAX_NUMBER", "0000000000")
STORE_SLOGAN = os.getenv("STORE_SLOGAN", "Demo Sağlık, Güvenilir Seçimler")
STORE_INSTAGRAM_URL = os.getenv("STORE_INSTAGRAM_URL", "#")
STORE_LOGO = os.getenv("STORE_LOGO", "images/demo-logo.svg")
ADMIN_NOTIFICATION_EMAIL = os.getenv("ADMIN_NOTIFICATION_EMAIL", "admin@example.com")

IYZICO_CALLBACK_URL = (
    f"{APP_BASE_URL}/odeme/iyzico/callback/"
)
IYZICO_SUCCESS_URL = (
    f"{APP_BASE_URL}/odeme/iyzico/success/"
)
IYZICO_ERROR_URL = (
    f"{APP_BASE_URL}/odeme/iyzico/error/"
)

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "noreply@example.com",
)

SITE_ID = 1

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "payments": {
            "handlers": ["console"],
            "level": os.getenv("PAYMENTS_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}