# Generated by Django 5.1.4 on 2025-05-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='e_invoice_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
