# Generated by Django 5.1.4 on 2025-12-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_e_invoice_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_contract_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_sales_contract_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pre_information_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pre_information_text',
            field=models.TextField(blank=True),
        ),
    ]
