# Generated by Django 5.1.4 on 2025-12-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_approved_at_order_distance_contract_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='approved_at',
            new_name='contracts_approved_at',
        ),
        migrations.AddField(
            model_name='order',
            name='contract_version',
            field=models.CharField(default='MS-2025-01', max_length=20),
        ),
    ]
