# Generated by Django 5.1.4 on 2025-12-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_approved_at_order_contracts_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guest_email',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('iyzico', 'Iyzico'), ('akbank', 'Akbank')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('awaiting_contracts', 'Sözleşme Bekleniyor'), ('awaiting_payment', 'Ödeme Bekleniyor'), ('paid', 'Ödendi'), ('payment_failed', 'Ödeme Başarısız'), ('approved', 'Onaylandı'), ('preparing', 'Hazırlanıyor'), ('shipped', 'Kargoya Verildi'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], default='draft', max_length=30),
        ),
    ]
