# Generated by Django 5.1.4 on 2026-01-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shipping_address_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('free_shipping_limit', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sipariş Ayarı',
                'verbose_name_plural': 'Sipariş Ayarları',
            },
        ),
    ]
