# Generated by Django 5.1.4 on 2026-01-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
