# Generated by Django 5.1.4 on 2026-01-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'İade Onaylandı (MNG Kodu Verildi)'), ('received', 'Ürün Geldi, İnceleniyor'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20),
        ),
    ]
