# Generated by Django 5.1.4 on 2026-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_identity_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik Numarası (Fatura için)'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_type',
            field=models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal'), ('sole_proprietor', 'Şahıs Şirketi')], default='individual', max_length=20, verbose_name='Fatura Tipi'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi Numarası'),
        ),
    ]
