# Generated by Django 5.1.4 on 2026-01-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_invoice_identity_number_order_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True, null=True, verbose_name='Fatura Adresi'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fatura Şehir'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(blank=True, default='Türkiye', max_length=30, null=True, verbose_name='Fatura Ülke'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatura İlçe'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fatura Adı Soyadı'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fatura Telefon'),
        ),
    ]
