# Generated by Django 5.1.4 on 2026-01-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(default=False, verbose_name='Renk Seçeneği Var mı?'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=False, verbose_name='Beden Seçeneği Var mı?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Beden')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Ürün Varyantı',
                'verbose_name_plural': 'Ürün Varyantları',
                'indexes': [models.Index(fields=['product', 'size', 'color'], name='products_pr_product_fb9cfd_idx')],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
